In [2]:
import numpy as np
np.full(2, 3)

array([3, 3])

In [1]:
import numpy as np
m = np.random.randn(3, 3)

argmin = np.unravel_index(np.argmin(m), m.shape)
print(argmin)
m

(1, 1)


array([[-0.46082469,  2.92764047,  0.09038748],
       [ 0.76530244, -0.6120313 ,  0.57267539],
       [ 0.95905402, -0.37432379,  0.45727335]])

In [3]:
np.zeros((2, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])